openapi: 3.0.3
info:
  title: TickTack API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: timesheet
    description: Everything needed for the timesheet
  - name: settings
    description: Everything about settings

paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong

  /getWeeksAll:
    get:
      tags:
        - timesheet
      summary: get all weeks
      description: get all weeks
      operationId: getWeeksAll
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeeksArray'
        '500':
          description: Server error
  
  /saveWeek:
    post:
      tags:
        - timesheet
      summary: save week with time entries
      description: save week with time entries
      operationId: saveWeek
      requestBody:
        description: entry you want to send
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Week'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '422':
          description: Validation exception

  /saveSettings:
    post:
      tags:
        - settings
      summary: save current settings
      description: save current settings
      operationId: saveSettings
      requestBody:
        description: settings to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '422':
          description: Validation exception

  /getSettings:
    get:
      tags:
        - settings
      summary: get saved settings
      description: get saved settings
      operationId: getSettings
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'
        '500':
          description: Server error

  /getWorkedHoursCurrWeek:
    get:
      tags:
        - timesheet
      summary: get total worked hours for the current week
      description: get total worked hours for the current week
      operationId: getWorkedHoursCurrWeek
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                example: "35:42"
        '500':
          description: Server error


components:
  schemas:
    WeeksArray:
      title: Weeks Array
      description: array containing weeks
      type: array
      items:
        $ref: '#/components/schemas/Week'

    Week:
      title: Week object
      description: object with time entries for one week
      type: object
      properties:
        year:
          type: integer
          example: 2024
        cw:
          type: integer
          example: 20
        totalHoursWorked:
          type: number
          format: float
          example: 38.5
        timeEntries:
          type: array
          items:
            $ref: '#/components/schemas/TimeEntry'

    TimeEntry:
      title: time entry
      description: time entry with start and end time
      type: object
      properties:
        id:
          type: integer
          example: 1
        day:
          type: string
          example: 'MONDAY'
        date:
          type: string
          example: "13.05.24"
        startTime:
          type: string
          example: "06:50"
        endTime:
          type: string
          example: "15:50"

    Settings:
      title: settings
      description: settings defining the weekly working hours and break duration
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_name:
          type: string
          example: Hans
        weekly_hours:
          type: number
          format: float
          example: 38.5
        break_duration:
          type: integer
          example: 45


